=== dexmagic/nasa-goddard-irc/irc_v6/resources/xml/schema/psml.xsd
<?xml version="1.0"?>
<!--
#=========================================================================
#  This code was developed by NASA, Goddard Space Flight Center, Code 580
#  for the Instrument Remote Control (IRC) project.
#== Warning ============================================================== 
#  This software is property of the National Aeronautics and Space
#  Administration. Unauthorized use or duplication of this software is
#  strictly prohibited. Authorized users are subject to the following
#  restrictions:
#  * Neither the author, their corporation, nor NASA is responsible for
#    any consequence of the use of this software.
#  * The origin of this software must not be misrepresented either by
#    explicit claim or by omission.
#  * Altered versions of this software must be plainly marked as such.
#  * This notice may not be removed or altered.
#=========================================================================
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="ParameterSet" type="ParameterSetType"/>
	<!--ParameterSetType:-->
	<xsd:complexType name="ParameterSetType">
		<xsd:sequence>
			<xsd:element name="InputOutputSpecification" type="InputOutputSpecificationType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Parameter" type="ParameterType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="type" type="xsd:string" use="required"/>
	</xsd:complexType>
	<!--InputOutputSpecificationType: -->
	<xsd:complexType name="InputOutputSpecificationType">
		<xsd:sequence>
			<xsd:element name="Input" type="IOType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Output" type="IOType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="optional"/>
	</xsd:complexType>
	<!--IOType: -->
	<xsd:complexType name="IOType">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="unit" type="xsd:string"/>
	</xsd:complexType>
	<!--ParameterType: -->
	<xsd:complexType name="ParameterType">
		<xsd:sequence>
			<xsd:element name="Value" type="ValueType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>
	<!--ValueType: -->
	<xsd:complexType name="ValueType">
		<xsd:attribute name="name" type="xsd:string" use="optional"/>
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== dexmagic/nasa-goddard-irc/irc_v6/resources/xml/parametersets/sample_scale_channel_parameterset.xml
<?xml version="1.0" encoding="UTF-8"?>
<ParameterSet name="Scale" type="Channel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="psml.xsd">

	<Parameter name="ADC[0,0]">
		<Value value="0"/>
	</Parameter>
	<Parameter name="ADC[0,1]">
		<Value value="0.1"/>
	</Parameter>
	<Parameter name="ADC[0,2]">
		<Value value="0.2"/>
	</Parameter>
	<Parameter name="ADC[0,3]">
		<Value value="0.3"/>
	</Parameter>

	<Parameter name="ADC[1,0]">
		<Value value="1.0"/>
	</Parameter>
	<Parameter name="ADC[1,1]">
		<Value value="1.1"/>
	</Parameter>
	<Parameter name="ADC[1,2]">
		<Value value="1.2"/>
	</Parameter>
	<Parameter name="ADC[1,3]">
		<Value value="1.3"/>
	</Parameter>

	<Parameter name="ADC[2,0]">
		<Value value="2.0"/>
	</Parameter>
	<Parameter name="ADC[2,1]">
		<Value value="2.1"/>
	</Parameter>
	<Parameter name="ADC[2,2]">
		<Value value="2.2"/>
	</Parameter>
	<Parameter name="ADC[2,3]">
		<Value value="2.3"/>
	</Parameter>

	<Parameter name="ADC[3,0]">
		<Value value="3.0"/>
	</Parameter>
	<Parameter name="ADC[3,1]">
		<Value value="3.1"/>
	</Parameter>
	<Parameter name="ADC[3,2]">
		<Value value="3.2"/>
	</Parameter>
	<Parameter name="ADC[3,3]">
		<Value value="3.3"/>
	</Parameter>

	<Parameter name="ADC[4,0]">
		<Value value="4.0"/>
	</Parameter>
	<Parameter name="ADC[4,1]">
		<Value value="4.1"/>
	</Parameter>
	<Parameter name="ADC[4,2]">
		<Value value="4.2"/>
	</Parameter>
	<Parameter name="ADC[4,3]">
		<Value value="4.3"/>
	</Parameter>

	<Parameter name="ADC[5,0]">
		<Value value="5.0"/>
	</Parameter>
	<Parameter name="ADC[5,1]">
		<Value value="5.1"/>
	</Parameter>
	<Parameter name="ADC[5,2]">
		<Value value="5.2"/>
	</Parameter>
	<Parameter name="ADC[5,3]">
		<Value value="5.3"/>
	</Parameter>

	<Parameter name="ADC[6,0]">
		<Value value="6.0"/>
	</Parameter>
	<Parameter name="ADC[6,1]">
		<Value value="6.1"/>
	</Parameter>
	<Parameter name="ADC[6,2]">
		<Value value="6.2"/>
	</Parameter>
	<Parameter name="ADC[6,3]">
		<Value value="6.3"/>
	</Parameter>

	<Parameter name="ADC[7,0]">
		<Value value="7.0"/>
	</Parameter>
	<Parameter name="ADC[7,1]">
		<Value value="7.1"/>
	</Parameter>
	<Parameter name="ADC[7,2]">
		<Value value="7.2"/>
	</Parameter>
	<Parameter name="ADC[7,3]">
		<Value value="7.3"/>
	</Parameter>

	<Parameter name="DAC[0,0]">
		<Value value="0.0"/>
	</Parameter>
	<Parameter name="DAC[0,1]">
		<Value value="-0.1"/>
	</Parameter>
	<Parameter name="DAC[0,2]">
		<Value value="-0.2"/>
	</Parameter>
	<Parameter name="DAC[0,3]">
		<Value value="-0.3"/>
	</Parameter>

	<Parameter name="DAC[1,0]">
		<Value value="-1.0"/>
	</Parameter>
	<Parameter name="DAC[1,1]">
		<Value value="-1.1"/>
	</Parameter>
	<Parameter name="DAC[1,2]">
		<Value value="-1.2"/>
	</Parameter>
	<Parameter name="DAC[1,3]">
		<Value value="-1.3"/>
	</Parameter>

	<Parameter name="DAC[2,0]">
		<Value value="-2.0"/>
	</Parameter>
	<Parameter name="DAC[2,1]">
		<Value value="-2.1"/>
	</Parameter>
	<Parameter name="DAC[2,2]">
		<Value value="-2.2"/>
	</Parameter>
	<Parameter name="DAC[2,3]">
		<Value value="-2.3"/>
	</Parameter>

	<Parameter name="DAC[3,0]">
		<Value value="-3.0"/>
	</Parameter>
	<Parameter name="DAC[3,1]">
		<Value value="-3.1"/>
	</Parameter>
	<Parameter name="DAC[3,2]">
		<Value value="-3.2"/>
	</Parameter>
	<Parameter name="DAC[3,3]">
		<Value value="-3.3"/>
	</Parameter>

	<Parameter name="DAC[4,0]">
		<Value value="-4.0"/>
	</Parameter>
	<Parameter name="DAC[4,1]">
		<Value value="-4.1"/>
	</Parameter>
	<Parameter name="DAC[4,2]">
		<Value value="-4.2"/>
	</Parameter>
	<Parameter name="DAC[4,3]">
		<Value value="-4.3"/>
	</Parameter>

	<Parameter name="DAC[5,0]">
		<Value value="-5.0"/>
	</Parameter>
	<Parameter name="DAC[5,1]">
		<Value value="-5.1"/>
	</Parameter>
	<Parameter name="DAC[5,2]">
		<Value value="-5.2"/>
	</Parameter>
	<Parameter name="DAC[5,3]">
		<Value value="-5.3"/>
	</Parameter>

	<Parameter name="DAC[6,0]">
		<Value value="-6.0"/>
	</Parameter>
	<Parameter name="DAC[6,1]">
		<Value value="-6.1"/>
	</Parameter>
	<Parameter name="DAC[6,2]">
		<Value value="-6.2"/>
	</Parameter>
	<Parameter name="DAC[6,3]">
		<Value value="-6.3"/>
	</Parameter>

	<Parameter name="DAC[7,0]">
		<Value value="-7.0"/>
	</Parameter>
	<Parameter name="DAC[7,1]">
		<Value value="-7.1"/>
	</Parameter>
	<Parameter name="DAC[7,2]">
		<Value value="-7.2"/>
	</Parameter>
	<Parameter name="DAC[7,3]">
		<Value value="-7.3"/>
	</Parameter>
</ParameterSet>
